/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekakhir;

import controller.datagamecontroller;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author USER
 */

public class gameview extends javax.swing.JFrame {

    /**
     * Creates new form gameview
     */
    datagamecontroller dg;
    public gameview() {
        initComponents();
        reqgametitle.setVisible(false);
        reqgenre.setVisible(false);
        reqsize.setVisible(false);
        dg = new datagamecontroller(this);
        dg.isitabel1();
        dg.isitabel2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelreq = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelgame = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acceptreq = new javax.swing.JButton();
        declinereq = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        reqsize = new javax.swing.JTextField();
        reqgametitle = new javax.swing.JTextField();
        reqgenre = new javax.swing.JTextField();
        deletegame = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabelreq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelreq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelreqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelreq);

        tabelgame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelgameMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelgame);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("Requested Games");

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Installed Games");

        acceptreq.setText("Accept");
        acceptreq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptreqActionPerformed(evt);
            }
        });

        declinereq.setText("Decline");
        declinereq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declinereqActionPerformed(evt);
            }
        });

        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        reqsize.setText("       ");

        reqgametitle.setText("      ");
        reqgametitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqgametitleActionPerformed(evt);
            }
        });

        reqgenre.setText("       ");

        deletegame.setText("Uninstall Game");
        deletegame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletegameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(200, 200, 200))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(reqgenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(reqgametitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(reqsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(acceptreq, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(declinereq, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deletegame, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 48, Short.MAX_VALUE)
                        .addComponent(reqgametitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reqgenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reqsize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deletegame)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(acceptreq)
                                .addComponent(declinereq)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptreqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptreqActionPerformed
        dg.insert2(); 
        dg.isitabel2();
        dg.delete1();
        dg.isitabel1();
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptreqActionPerformed

    private void declinereqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declinereqActionPerformed
        dg.delete1();
        dg.isitabel1();
        dg.isitabel2();
        JOptionPane.showMessageDialog(null, "Request Ditolak");
    }//GEN-LAST:event_declinereqActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        adminview v = new adminview();
        v.setLocationRelativeTo(null);
        v.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabelreqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelreqMouseClicked
        int baris = tabelreq.getSelectedRow();
        reqgametitle.setText(tabelreq.getValueAt(baris, 0).toString());
        reqgenre.setText(tabelreq.getValueAt(baris, 1).toString());
        reqsize.setText(tabelreq.getValueAt(baris, 2).toString());
    }//GEN-LAST:event_tabelreqMouseClicked

    private void reqgametitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqgametitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reqgametitleActionPerformed

    private void tabelgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelgameMouseClicked
        int baris = tabelgame.getSelectedRow();
        reqgametitle.setText(tabelgame.getValueAt(baris, 0).toString());
        reqgenre.setText(tabelgame.getValueAt(baris, 1).toString());
        reqsize.setText(tabelgame.getValueAt(baris, 2).toString());        // TODO add your handling code here:
    }//GEN-LAST:event_tabelgameMouseClicked

    private void deletegameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletegameActionPerformed
        dg.delete2();        // TODO add your handling code here:
        dg.isitabel1();
        dg.isitabel2();
    }//GEN-LAST:event_deletegameActionPerformed

 
    public JTable getTabelgame() {
        return tabelgame;
    }

    public void setTabelgame(JTable tabelgame) {
        this.tabelgame = tabelgame;
    }

    public JTable getTabelreq() {
        return tabelreq;
    }

    public void setTabelreq(JTable tabelreq) {
        this.tabelreq = tabelreq;
    }

    public JTextField getReqgametitle() {
        return reqgametitle;
    }

    public void setReqgametitle(JTextField reqgametitle) {
        this.reqgametitle = reqgametitle;
    }

    public JTextField getReqgenre() {
        return reqgenre;
    }

    public void setReqgenre(JTextField reqgenre) {
        this.reqgenre = reqgenre;
    }

    public JTextField getReqsize() {
        return reqsize;
    }

    public void setReqsize(JTextField reqsize) {
        this.reqsize = reqsize;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptreq;
    private javax.swing.JButton declinereq;
    private javax.swing.JButton deletegame;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField reqgametitle;
    private javax.swing.JTextField reqgenre;
    private javax.swing.JTextField reqsize;
    private javax.swing.JTable tabelgame;
    private javax.swing.JTable tabelreq;
    // End of variables declaration//GEN-END:variables
}
